#!/bin/sh
###
# Home page: https://github.com/johntmcintosh/xcunsign/
# Author:   John T McIntosh (http://johntmcintosh.com)
###

MAC_OS_VERSION=$(sw_vers -productVersion)
MAC_OS_SIERRA="10.12"
if [ $(bc <<< "$MAC_OS_VERSION < $MAC_OS_SIERRA") -eq 1 ]
    then
echo "MacOS version checked and error handling activated"
set -o errexit # Exit if any statement returns a non-true return value (non-zero).
set -o nounset # Exit on use of an uninitialized variable
fi

# Get the source directory to use for relative paths when referencing other scripts
CALLING_DIR="${BASH_SOURCE%/*}"
BINARY=`readlink "$CALLING_DIR/xcunsign"`
if [ -n "$BINARY" ]; then
    ROOT_DIR=$(dirname $BINARY)
else
    ROOT_DIR=$CALLING_DIR
fi

# Parse the command line input
source "$ROOT_DIR/lib/input.sh"

# If the app is already signed, there's nothing that needs to be done
if $ROOT_DIR/lib/verify_codesign.rb "$BINARY_PATH"; then 
    echo "${GREEN}$BINARY_PATH is already signed.${NC}"
    exit 0
fi

# Ensure that the app has a signed copy that can be restored
# If the return code of the verify_codesign call is 0, then
# we have a legitimately signed binary.
if ! $ROOT_DIR/lib/verify_codesign.rb "$SIGNED_PATH"; then
    echo "${RED}There no file at ${SIGNED_PATH} to restore.${NC}"
    exit 1 
fi

# Delete the existing binary, and replace it with the signed copy
echo "Deleting unsigned Xcode binary."
rm "$BINARY_PATH"

echo "Setting $BINARY_PATH to signed copy"
mv "$SIGNED_PATH" "$BINARY_PATH"

echo "Signed binary restored."

# Restore Xcode's app icon to the standard icon
$ROOT_DIR/bin/fileicon rm $XCODE_PATH
killall Finder
killall Dock

echo "${GREEN}Xcode $INPUT_VERSION signature has been restored.${NC}"
