#!/bin/sh
###
# Home page: https://github.com/johntmcintosh/xcunsign/
# Author:   John T McIntosh (http://johntmcintosh.com)
###

set -o errexit # Exit if any statement returns a non-true return value (non-zero).
set -o nounset # Exit on use of an uninitialized variable

# Get the source directory to use for relative paths when referencing other scripts
CALLING_DIR="${BASH_SOURCE%/*}"
BINARY=`readlink "$CALLING_DIR/xcunsign"`
if [ -n "$BINARY" ]; then
    ROOT_DIR=$(dirname $BINARY)
else
    ROOT_DIR=$CALLING_DIR
fi

# Parse the command line input
source "$ROOT_DIR/lib/input.sh"

# If the app is already unsigned, there's nothing that needs to be done
if ! $ROOT_DIR/lib/verify_codesign.rb "$BINARY_PATH"; then
    echo "${GREEN}$BINARY_PATH is already unsigned.${NC}"
    exit 0
fi

# echo "Executing unsign now..."
echo "The app is currently signed. Executing unsign now..."
$ROOT_DIR/bin/unsign $BINARY_PATH $UNSIGNED_PATH

# Rename the original binary so it can later be restored.
echo "Renaming Xcode to Xcode.signed."
mv "$BINARY_PATH" "$SIGNED_PATH"

# Rename the unsigned binary so it will be primary
echo "Renaming Xcode.unsigned to Xcode."
mv "$UNSIGNED_PATH" "$BINARY_PATH"

# Set Xcode's app icon to the unsigned icon
$ROOT_DIR/bin/fileicon set $XCODE_PATH $ROOT_DIR/resources/XcodeUnsigned.png
killall Finder
killall Dock

echo "${GREEN}Xcode $INPUT_VERSION has been unsigned.${NC}"
